Hospital/Hospital/urls.py
from django.contrib import admin
from django.urls import path,include
from django .conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("register.urls")),
    path("",include("blog.urls")),
     path("",include("appoint.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Hospital/appoint/urls.py
from django.contrib import admin
from django.urls import path
from django .conf import settings
from django.conf.urls.static import static
from appoint import views
app_name="appoint"
urlpatterns = [
    path('admin/', admin.site.urls),

# path('delete/<str:p>',views.delete,name='delete'),

path('doctors',views.doctors,name='doctors'),
 path('viewevent' , views.viewevent , name='viewevent    '),
    path('confirm' , views.confirm , name='confirm'),
    path('bookform/<str:pk>/' , views.bookform , name='bookform'),

]

Hospital/blog/urls.py
from django.contrib import admin
from django.urls import path
from django .conf import settings
from django.conf.urls.static import static
from blog import views
app_name="blog"
urlpatterns = [
    path('admin/', admin.site.urls),
path("create_post",views.create_post,name="create_post"),
path("view_post",views.view_post,name="view_post"),
path("draft",views.draft,name="draft"),
path('delete/<str:p>',views.delete,name='delete'),
path('delete_draft/<str:p>',views.delete_draft,name='delete_draft'),
path('category_post',views.category_post,name='category_post'),
path('postview/<str:p>',views.postview,name='postview'),
]

Hospital/blog/models.py
from django.db import models

class post(models.Model):
    category = ( 
    ("Covid19", "Covid19"), 
    ("Heart Disease", "Heart Disease"),
    ("Immunization","Immunization"), 
    ("Mental Health","Mental Health"),    
    ) 
    category = models.CharField(max_length=50,choices = category)
    title = models.CharField(max_length=500)
    image = models.ImageField(upload_to="blog/")
    summary = models.TextField()
    content = models.TextField()
    draft = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
# Create your models here.

Hospital/templates/bookform.html
{% extends 'base.html' %}
{% block content %}
<div class="contact-form-main" style="height: 500px;"><br><br>
  <div class="container mb-3" style="background-color: rgb(127, 214, 255);position: relative;height: 400px;">
      
                 
                      <div class="row ">
<div class="container emp-profile">
    
        
           
           <br><br>
            <h2 class="register-heading mb-3" style="position: relative;left:450px">Book Apoinment For {{user}}</h2>
<form method="post" action=''>

    {% csrf_token %}
    <br><br>
    <div class="form-group">
      <label style="position: relative;right:1px;font-size: 14px;color: black;"><b>Required Speciality:</b></label>
    <input type="text" name="req" class="form-control" style="font-size: 18px;">
    </div>
    <div class="form-group"><label style="position: relative;right:1px;font-size: 14px;color: black;"><b>Date of Appointment:</b></label>
    <input type="date" name='start' class="form-control"  placeholder="Date of Appointment" style="font-size: 18px;"> </div>
    <div class="form-group">
      <label style="position: relative;right:1px;font-size: 14px;color: black;"><b>Start Time of Appointment:</b></label>
    <input type="time" name='time'class="form-control" style="font-size: 18px;"></div>
    <input type="email" name='email'class="form-control" hidden value={{form.email}}></div>

    <input type="submit" value="Confirm" class="btn btn" style="position: relative;left:550px;"> 
</div></div></div>
{%endblock%}


</form>
  </html>

Hospital/templates/category_post.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
     <!--? Contact form Start -->
     <div class="contact-form-main" style="height: 520px;">
        <div class="container" style="background-color: rgb(127, 214, 255);position: relative;top:70px;height: 450px;">
            
                       
                            <div class="row ">
                               
                                        
                                        <!-- <h2>Appointment Form</h2> -->
                         
                        <!--End Section Tittle  -->
                        <!-- <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <table style="position: relative;left: 50px;">
                            {{form.as_table}}
                           
                            </table>
                            <input type="submit" style="position: relative;left: 50px;">
                            </form> -->
                            {% if posts %}
                            {% for i in posts %}
                  
                            <div class="col-sm-4" style="margin-bottom: 50px;"><div class="card m-5" style="width: 20rem;height: 100px;" >
                                  <!-- <img src="{{i.image.url}}" class="card-img-top height=100px" alt="..." width="100%" style="height: 250px;"> -->
                                  <div class="card-body">
                                   
                                  


                          <a class="btn btn-danger" href="{% url 'blog:postview' i.category %}" >{{i.category}}</a>
                                  </div>
                                </div></div>
                                {% endfor %}
                                {% else %}
                                {% if messages %}
                                {% for messsage in messages %}
                              
                                <div class='chip green white-text' style="color:red;font-size: 40px;position: relative;left:350px;top:100px;">{{messsage}}</div>
                                <a class="btn btn-danger" href="{% url 'blog:view_post' %}" style="position: relative;top:200px;">View Post</a>
                               {% endfor %}
                               {% endif %}
                                {% endif %}
                    </div>
                </div>
            </div>
        
        <!-- contact left Img-->
        <!-- <div class="from-left d-none d-lg-block">
            <img src="{% static 'img/gallery/contact_form.png' %}" alt="">
        </div> -->
    </div>
    <!-- Contact form End -->
{% endblock %}

Hospital/templates/confirm.html
{% extends 'base.html' %}
{% block content %}
<div class="contact-form-main" style="height: 420px;">
    <div class="container" style="background-color: rgb(127, 214, 255);position: relative;top:70px;height: 350px;">
    
        
           <div  style="text-align:justify;">
            
<h2> Doctor name       :{{form.first_name}}</h2>

<h2> appointment date :{{start}}</h2>
<h2> start time :{{time}}</h2>
<h2> end time :{{end_time}}</h2><br><br>
<h3 style="font-size:14;color:rgb(237, 20, 52)">Your Booking is Successful.Event will be stored in Doctor's email's google calendar</h3>
    <form method="post" >
        {% csrf_token %}
    
    <input type="text" class="form-control" value="{{req}}" name="required" hidden>
    <input type="date" class="form-control" value="{{start}}" name="starts" hidden>
    <input type="time" class="form-control" value="{{time}}" name="time" hidden>
    <input type="email" name='email'class="form-control" hidden value={{email}}>
 
 
    </form>
</div>
    </div>
</div>
{%endblock%}

Hospital/templates/create_post.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
     <!--? Contact form Start -->
     <div class="contact-form-main" >
        <div class="container" >
            <div class="row justify-content-end">
                <div class="col-xl-7 col-lg-7" style="position: relative;left:100px;">
                    <div class="form-wrapper" >
                        <!--Section Tittle  -->
                        {% if messages %}
                        {% for messsage in messages %}
                      
                        <div class='chip green white-text' style="color:red;font-size: 20px;position: relative;left:80px;top:80px;">{{messsage}}</div>
                       {% endfor %}
                       {% endif %}
                        <div class="form-tittle">
                            <div class="row ">
                                <div class="col-xl-12">
                                    <!-- <div class="section-tittle section-tittle2"> -->
                                        <h1>Create Your Post</h1>
                                        <br><br>
                                        <!-- <h2>Appointment Form</h2> -->
                                    <!-- </div> -->
                                </div>
                            </div>
                        </div>
                        <!--End Section Tittle  -->
                        <!-- <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <table style="position: relative;left: 50px;">
                            {{form.as_table}}
                           
                            </table>
                            <input type="submit" style="position: relative;left: 50px;">
                            </form> -->
                        <form  method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-6 col-md-6">
                                    <div class="form-box user-icon mb-30">
                                        <label style="color: black;font-size: 15px;position: relative;left:25px;">Title:
                                        <input type="text" name="title" placeholder="Enter Title Here" style="font-size: 20px;"  required class="validate"/></label>
                                    </div>
                                </div>
                                <div class="col-lg-12 col-md-6">
                                    <div class="form-box subject-icon mb-30">
                                <label style="color: black;font-size: 15px;position: relative;left:25px;">Image:<input type="file" name="image" required class="validate" ></label>
                                
                                    </div></div>
                                <div class="col-lg-12 col-md-6">
                                    <div class="form-box user-icon mb-30">
                                        <label style="color: black;font-size: 15px;">Category</label>
  <select class="browser-default" name="category"  required class="validate" style="position:relative;bottom:200px;">
    <option value="Covid19">Covid19</option>
    <option value="Heart Disease">Heart Disease</option>
    <option value="Immunization">Immunization</option>
    <option value="Mental Health">Mental Health</option>

  </select>
                                    </div>
                                </div>
                                <div class="col-lg-12 col-md-6 mb-30">
                                    <div class="form-box user-icon mb-30">
                                        <label class="form-label" style="font-size: 15px;">Summary:</label>
                                        <textarea name="summary" id="summary"  style="font-size: 20px;position: relative;left:10px;" required class="validate"></textarea>
                                    </div>
                                </div>
                                <div class="col-lg-12 col-md-6 mb-30">
                                    <div class="form-box user-icon mb-30">
                                        <label class="form-label" style="font-size: 15px;">Content:</label>
                                        <textarea name="content" id="content"  style="font-size: 20px;position: relative;left:10px;" required class="validate"></textarea>
                                    </div>
                                </div>
                                <div class="col-lg-12 col-md-6">
                                    <div class="form-box subject-icon mb-30">
                                        <label for="id_draft" style="font-size: 15px;">Draft:</label>
                                        <input type="checkbox" name="draft" id="id_draft" >
                                    </div>
                                </div>
                              
                              
                                
                                    <div class="submit-info">
                                        <input type="submit" value="Create Post" name="create_post" class="btn btn-large" style="color:white;background-color:rgb(34, 87, 246) ;position: relative;left: 15px;">
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- contact left Img-->
        <div class="from-left d-none d-lg-block">
            <img src="{% static 'img/logo/logo.png' %}" alt="" style="height: 200px;width: 500px;position:relative;bottom:600px;left:100px">
        </div>
    </div>
    <!-- Contact form End -->
{% endblock %}

Hospital/templates/doctor_home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--? About Start-->
<br><br>
<div class="about-area mt-2">
    <h3 style="font-size: 40px;"><b style="color: black;position: relative;left:320px;top: 80px;">Welcome To Our Hospital</b></h3>
    <div class="container" style="height: 800px;position:relative;top:80px;">
        <div class="row">
            <div class="col-lg-6 col-md-10">
                <div class="about-caption mb-50"> 
                    <!-- Section Tittle -->
                    <div class="about-img ">
                        <!-- <div class="about-font-img d-none d-lg-block">
                            <img src="{% static 'img/gallery/ba.jpg' %}" alt="" style="height: 400px;width: 400px;">
                        </div> -->
                        <div class="about-back-img ">
                            {% if  data %}
                            <img src="{{data.profile_pic.url}}" alt="" style="height: 400px;width: 400px;">
                            {% endif %}
                        </div>
                    </div>
                    
                    
                  
                </div>
            </div>
            <div class="col-lg-6 col-md-12"> 
                <!-- about-img -->
                <div class="section-tittle section-tittle2 mb-35">
                    <br><br><br>

                  <br><br>
                       {% if  data %}
                       <h3 style="font-size: 30px;"><b style="color: black;"><u>Doctor Profile</u></b></h3>
                       <ul  style="color:black;font-size: 25px; position: relative;bottom: 100px;left:10px">
                         
                         <li style="position: relative;top:130px;font-size: 25px;"><b style="color: black;">First Name:{{data.first_name}}</b></li>
                         <li style="position: relative;top:160px;font-size: 25px;"><b style="color: black;">Last Name:{{data.last_name}}</b></li>
                         <li style="position: relative;top:190px;font-size: 25px;"><b style="color: black;">Email Id:{{data.email}}</b></li>
                         <li style="position: relative;top:220px;font-size: 25px;"><b style="color: black;">Address:{{data.address}}</b></li>
                       </ul> 
             {% endif %}
                   </div>
            </div>
        </div>
    </div>
</div> 
{% endblock %}

Hospital/templates/doctors.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--? Contact form Start -->
<div class="contact-form-main" style="height: 920px;">
    <div class="container" style="background-color: rgb(127, 214, 255);position: relative;top:70px;height: 650px;">
        
                   
                        <div class="row ">
                           
                                    
                                    <!-- <h2>Appointment Form</h2> -->
                     
                    <!--End Section Tittle  -->
                    <!-- <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <table style="position: relative;left: 50px;">
                        {{form.as_table}}
                       
                        </table>
                        <input type="submit" style="position: relative;left: 50px;">
                        </form> -->
                        {% if doctors %}
                        {% for i in doctors %}
              
                        <div class="col-sm-4" style="margin-bottom: 50px;"><div class="card m-5" style="width: 20rem;height: 450px;" >
                              <img src="{{i.profile_pic.url}}" class="card-img-top height=100px" alt="..." width="100%" style="height: 250px;">
                              <div class="card-body">
                               <h4 class="card-title" style=" font-family: Georgia, 'Times New Roman', Times, serif; font-weight: bold; color: black; text-align: center;">{{i.username}}</h4>
                              
        
                              <!-- <a class="btn btn-danger" href="" >Edit</a><br><br> -->
                      <a class="btn btn-danger" href="{% url 'appoint:bookform' i.id %}" style="position: relative;left:4px; width: 160px;color: black;text-align: center;">Book Appointment</a>
                              </div>
                            </div></div>
                            {% endfor %}
                            {% else %}
                            {% if messages %}
                            {% for messsage in messages %}
                          
                            <div class='chip green white-text' style="color:red;font-size: 40px;position: relative;left:350px;top:100px;">{{messsage}}</div>
                            <a class="btn btn-danger" href="{% url 'blog:view_post' %}" style="position: relative;top:200px;">View Post</a>
                           {% endfor %}
                           {% endif %}
                            {% endif %}
                </div>
            </div>
        </div>
    
    <!-- contact left Img-->
    <!-- <div class="from-left d-none d-lg-block">
        <img src="{% static 'img/gallery/contact_form.png' %}" alt="">
    </div> -->
</div>
<!-- Contact form End -->
{% endblock %}

Hospital/templates/draft.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
     <!--? Contact form Start -->
     <div class="contact-form-main" style="height: 820px;">
        <div class="container" style="background-color: rgb(127, 214, 255);position: relative;top:70px;height: 650px;">
            
                       
                            <div class="row ">
                               
                                        
                                        <!-- <h2>Appointment Form</h2> -->
                         
                        <!--End Section Tittle  -->
                        <!-- <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <table style="position: relative;left: 50px;">
                            {{form.as_table}}
                           
                            </table>
                            <input type="submit" style="position: relative;left: 50px;">
                            </form> -->
                            {% if posts %}
                            {% for i in posts %}
                  
                            <div class="col-sm-4" style="margin-bottom: 50px;"><div class="card m-5" style="width: 20rem;height: 500px;" >
                                  <img src="{{i.image.url}}" class="card-img-top height=100px" alt="..." width="100%" style="height: 250px;">
                                  <div class="card-body">
                                    <h4 class="card-title" style=" font-family: Georgia, 'Times New Roman', Times, serif; font-weight: bold; color: black;">{{i.title}}</h4>
                                  
                                    <h4 class="card-title" style="font-family: 'Times New Roman', Times, serif; color: black;"><b>Summary:</b>{{i.summary|truncatewords:15}}</h4>
                                  <!-- <a class="btn btn-danger" href="" >Edit</a><br><br> -->
                           <a class="btn btn-danger" href="{% url 'blog:delete_draft' i.title %}" >Delete</a> 
                                  </div>
                                </div></div>
                                {% endfor %}
                                {% else %}
                                {% if messages %}
                                {% for messsage in messages %}
                              
                                <div class='chip green white-text' style="color:red;font-size: 40px;position: relative;left:350px;top:100px;">{{messsage}}</div>
                                <a class="btn btn-danger" href="{% url 'blog:draft' %}" style="position: relative;top:200px;">View Draft</a>
                               {% endfor %}
                               {% endif %}
                                {% endif %}
                    </div>
                </div>
            </div>
        
        <!-- contact left Img-->
        <!-- <div class="from-left d-none d-lg-block">
            <img src="{% static 'img/gallery/contact_form.png' %}" alt="">
        </div> -->
    </div>
    <!-- Contact form End -->
{% endblock %}

Hospital/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
    <!--? slider Area Start-->
    <div class="slider-area position-relative">
        <div class="slider-active">
            <!-- Single Slider -->
            <div class="single-slider slider-height d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-7 col-lg-9 col-md-8 col-sm-9">
                            <div class="hero__caption">
                                <span>Committed to success</span>
                                <h1 class="cd-headline letters scale">We care about your 
                                    <strong class="cd-words-wrapper">
                                        <b class="is-visible">health</b>
                                        <!-- <b>sushi</b>
                                        <b>steak</b> -->
                                    </strong>
                                </h1>
                                <p data-animation="fadeInLeft" data-delay="0.1s">To keep the body in good health is a duty..otherwise we shall not be able to keep our mind strong and clear.</p>
                                <a href="#" class="btn hero-btn" data-animation="fadeInLeft" data-delay="0.5s">Appointment <i class="ti-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>          
            </div>
            <!-- Single Slider -->
            <div class="single-slider slider-height d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-7 col-lg-9 col-md-8 col-sm-9">
                            <div class="hero__caption">
                                <span>Committed to success</span>
                                <h1 class="cd-headline letters scale">We care about your 
                                    <strong class="cd-words-wrapper">
                                        <b class="is-visible">health</b>
                                        <!-- <b>sushi</b>
                                        <b>steak</b> -->
                                    </strong>
                                </h1>
                                <p data-animation="fadeInLeft" data-delay="0.1s">To keep the body in good health is a duty... otherwise we shall not be able to keep our mind strong and clear.</p>
                                <a href="#" class="btn hero-btn" data-animation="fadeInLeft" data-delay="0.5s">Appointment <i class="ti-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>          
            </div>
        </div>
    </div>
</main>
{% endblock %}

Hospital/templates/postview.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
     <!--? Contact form Start -->
     <div class="contact-form-main" style="height: 920px;">
        <div class="container" style="background-color: rgb(127, 214, 255);position: relative;top:70px;height: 550px;">
            
                       
                            <div class="row ">
                               
                                        
                                        <!-- <h2>Appointment Form</h2> -->
                         
                        <!--End Section Tittle  -->
                        <!-- <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <table style="position: relative;left: 50px;">
                            {{form.as_table}}
                           
                            </table>
                            <input type="submit" style="position: relative;left: 50px;">
                            </form> -->
                            {% if posts %}
                            {% for i in posts %}
                  
                            <div class="col-sm-6" style="margin-bottom: 50px;"><div class="card m-5" style="width: 500px;height: 300px;" >
                                  <img src="{{i.image.url}}" class="card-img-top height=100px" alt="..." width="100%" style="height: 300px;">
                                  <div class="card-body">
                                   <h5 class="card-title" style=" font-family: Georgia, 'Times New Roman', Times, serif; font-weight: bold; color: black;font-size: 20px;">Title:{{i.title}}</h5>
                                  
                                  <p class="card-title" style="font-family: 'Times New Roman', Times, serif; color: black;font-weight: bold;font-size: 20px;">Summary:{{i.summary|truncatewords:15}}</p>
                               
                                  </div>
                                </div></div>
                                {% endfor %}
                                {% else %}
                                {% if messages %}
                                {% for messsage in messages %}
                              
                                <div class='chip green white-text' style="color:red;font-size: 40px;position: relative;left:350px;top:100px;">{{messsage}}</div>
                                <a class="btn btn-danger" href="{% url 'blog:view_post' %}" style="position: relative;top:200px;">View Post</a>
                               {% endfor %}
                               {% endif %}
                                {% endif %}
                    </div>
                </div>
            </div>
        
        <!-- contact left Img-->
        <!-- <div class="from-left d-none d-lg-block">
            <img src="{% static 'img/gallery/contact_form.png' %}" alt="">
        </div> -->
    </div>
    <!-- Contact form End -->
{% endblock %}

Hospital/templates/view_post.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
     <!--? Contact form Start -->
     <div class="contact-form-main" style="height: 920px;">
        <div class="container" style="background-color: rgb(127, 214, 255);position: relative;top:70px;height: 650px;">
            
                       
                            <div class="row ">
                               
                                        
                                        <!-- <h2>Appointment Form</h2> -->
                         
                        <!--End Section Tittle  -->
                        <!-- <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <table style="position: relative;left: 50px;">
                            {{form.as_table}}
                           
                            </table>
                            <input type="submit" style="position: relative;left: 50px;">
                            </form> -->
                            {% if posts %}
                            {% for i in posts %}
                  
                            <div class="col-sm-4" style="margin-bottom: 50px;"><div class="card m-5" style="width: 20rem;height: 500px;" >
                                  <img src="{{i.image.url}}" class="card-img-top height=100px" alt="..." width="100%" style="height: 250px;">
                                  <div class="card-body">
                                   <h4 class="card-title" style=" font-family: Georgia, 'Times New Roman', Times, serif; font-weight: bold; color: black;">{{i.title}}</h4>
                                  
                                  <h4 class="card-title" style="font-family: 'Times New Roman', Times, serif; color: black;"><b>Summary:</b>{{i.summary|truncatewords:15}}</h4>
                                  <!-- <a class="btn btn-danger" href="" >Edit</a><br><br> -->
                          <a class="btn btn-danger" href="{% url 'blog:delete' i.title %}" >Delete</a>
                                  </div>
                                </div></div>
                                {% endfor %}
                                {% else %}
                                {% if messages %}
                                {% for messsage in messages %}
                              
                                <div class='chip green white-text' style="color:red;font-size: 40px;position: relative;left:350px;top:100px;">{{messsage}}</div>
                                <a class="btn btn-danger" href="{% url 'blog:view_post' %}" style="position: relative;top:200px;">View Post</a>
                               {% endfor %}
                               {% endif %}
                                {% endif %}
                    </div>
                </div>
            </div>
        
        <!-- contact left Img-->
        <!-- <div class="from-left d-none d-lg-block">
            <img src="{% static 'img/gallery/contact_form.png' %}" alt="">
        </div> -->
    </div>
    <!-- Contact form End -->
{% endblock %}